apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}-admin-frontend
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
    {{- include "webapp.adminFrontend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "webapp.adminFrontend.selectorLabels" . | nindent 4 }}
