apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}-backend
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
    {{- include "webapp.backend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
    - name: admin
      port: {{ .Values.backend.adminPort }}
      targetPort: admin
  selector:
    {{- include "webapp.backend.selectorLabels" . | nindent 4 }}
