{{- if .Values.backend.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-backend-secret
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.backend.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.frontend.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-frontend-secret
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.frontend.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.adminFrontend.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-admin-frontend-secret
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.adminFrontend.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
